'use strict';

const acids = [
 {id:'hcl_dil',name:'حمض الهيدروكلوريك المخفف',formula:'HCl (مخفف)',aliases:'هيدروكلوريك كلوريد الهيدروجين hcl مخفف مجموعة اولى',strength:'مخفف'},
 {id:'h2so4_dil',name:'حمض الكبريتيك المخفف',formula:'H₂SO₄ (مخفف)',aliases:'كبريتيك h2so4 مخفف حمض الكبريت',strength:'مخفف'},
 {id:'h2so4_conc',name:'حمض الكبريتيك المركز',formula:'H₂SO₄ (مركز)',aliases:'كبريتيك h2so4 مركز المجموعة الثانية',strength:'مركز'},
 {id:'hno3_dil',name:'حمض النيتريك المخفف',formula:'HNO₃ (مخفف)',aliases:'نيتريك hno3 مخفف',strength:'مخفف'},
 {id:'acetic',name:'حمض الإيثانويك (الأسيتيك)',formula:'CH₃COOH',aliases:'اسيتيك الخل ch3cooh حمض الخليك',strength:'حمض ضعيف'}
];
const salts = [
 {id:'carbonate',name:'كربونات الصوديوم',formula:'Na₂CO₃',aliases:'كربونات الصوديوم soda carbonate'},
 {id:'bicarbonate',name:'بيكربونات الصوديوم',formula:'NaHCO₃',aliases:'بيكربونات هيدروجين كربونات الصوديوم'},
 {id:'sulfite',name:'كبريتيت الصوديوم',formula:'Na₂SO₃',aliases:'كبريتيت صوديوم sulfite'},
 {id:'thiosulfate',name:'ثيوكبريتات الصوديوم',formula:'Na₂S₂O₃',aliases:'ثيو كبريتات الصوديوم'},
 {id:'sulfide',name:'كبريتيد الصوديوم',formula:'Na₂S',aliases:'كبريتيد الصوديوم sulfide'},
 {id:'nitrite',name:'نيتريت الصوديوم',formula:'NaNO₂',aliases:'نيتريت sodium nitrite'},
 {id:'chloride',name:'كلوريد الصوديوم',formula:'NaCl',aliases:'ملح الطعام كلوريد الصوديوم'},
 {id:'bromide',name:'بروميد البوتاسيوم',formula:'KBr',aliases:'بروميد البوتاسيوم'},
 {id:'iodide',name:'يوديد البوتاسيوم',formula:'KI',aliases:'يوديد البوتاسيوم'},
 {id:'silver_nitrate',name:'نترات الفضة',formula:'AgNO₃',aliases:'نترات فضة silver nitrate'},
 {id:'lead_nitrate',name:'نترات الرصاص الثنائي',formula:'Pb(NO₃)₂',aliases:'نترات الرصاص pb nitrate'},
 {id:'barium_chloride',name:'كلوريد الباريوم',formula:'BaCl₂',aliases:'كلوريد الباريوم كاشف الكبريتات'},
 {id:'sodium_sulfate',name:'كبريتات الصوديوم',formula:'Na₂SO₄',aliases:'كبريتات الصوديوم sulfate'},
 {id:'sodium_nitrate',name:'نترات الصوديوم',formula:'NaNO₃',aliases:'نترات الصوديوم nitrate'},
 {id:'potassium_nitrate',name:'نترات البوتاسيوم',formula:'KNO₃',aliases:'نترات البوتاسيوم'},
 {id:'sodium_phosphate',name:'فوسفات الصوديوم',formula:'Na₃PO₄',aliases:'فوسفات الصوديوم phosphate'},
 {id:'magnesium_sulfate',name:'كبريتات المغنيسيوم',formula:'MgSO₄',aliases:'كبريتات الماغنسيوم magnesium sulfate كاشف الكربونات والبيكربونات'},
 {id:'lead_acetate',name:'خلات الرصاص الثنائي',formula:'Pb(CH₃COO)₂',aliases:'اسيتات الرصاص خلات الرصاص lead acetate كاشف الكبريتيد'},
 {id:'calcium_chloride',name:'كلوريد الكالسيوم',formula:'CaCl₂',aliases:'كلوريد كالسيوم calcium chloride'},
 {id:'iron_ii_sulfate',name:'كبريتات الحديد الثنائي',formula:'FeSO₄',aliases:'كبريتات حديدوز ferrous sulfate'},
 {id:'copper_ii_sulfate',name:'كبريتات النحاس الثنائي',formula:'CuSO₄',aliases:'كبريتات النحاس copper sulfate'},
 {id:'zinc_chloride',name:'كلوريد الزنك',formula:'ZnCl₂',aliases:'كلوريد الخارصين zinc chloride'}
];
// Every result is tied to a specific acid–salt pair. An absent pair is marked unknown, not assumed to be “no reaction”.
const reactions = {
 'hcl_dil|carbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',gasColorLabel:'غاز عديم اللون والرائحة',gasTest:'ماء الجير الرائق يتعكر بسبب راسب أبيض من CaCO₃.',obs:'يحدث فوران ويتصاعد غاز CO₂ عديم اللون والرائحة. عند اختبار الغاز بماء الجير الرائق يتكوّن تعكّر أبيض.',conclusion:'يدل ذلك على وجود أيون الكربونات CO₃²⁻ في الملح. هذه ملاحظة مبدئية، ويُستكمل الكشف الاختباري كما في المنهج.',equation:'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',ionic:'CO₃²⁻ + 2H⁺ → H₂O + CO₂↑',explain:'الحمض يحرر حمض الكربونيك غير الثابت، فيتحلل إلى ماء وثاني أكسيد الكربون.',tags:['غاز','فوران'],
 },
 'hcl_dil|bicarbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',gasColorLabel:'غاز عديم اللون والرائحة',gasTest:'ماء الجير الرائق يتعكر بسبب راسب أبيض من CaCO₃.',obs:'يحدث فوران ويتصاعد غاز CO₂ عديم اللون والرائحة؛ ماء الجير الرائق يتعكر عند اختبار الغاز.',conclusion:'يتفق ذلك مع وجود أيون البيكربونات HCO₃⁻. للتفرقة عن الكربونات، استخدم الاختبار التأكيدي المقرر.',equation:'NaHCO₃ + HCl → NaCl + H₂O + CO₂↑',ionic:'HCO₃⁻ + H⁺ → H₂O + CO₂↑',explain:'يتفاعل أيون البيكربونات مع الحمض مطلقًا ثاني أكسيد الكربون.',tags:['غاز','فوران']},
 'hcl_dil|sulfite': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكبريت SO₂',obs:'يتصاعد غاز عديم اللون ذو رائحة نفاذة مميزة في الوصف الدراسي؛ لا يُشمّ الغاز في الواقع.',conclusion:'قد يدل ذلك على وجود أيون الكبريتيت SO₃²⁻. تُستخدم الاختبارات التأكيدية المقررة لتمييزه من الأيونات الأخرى.',equation:'Na₂SO₃ + 2HCl → 2NaCl + H₂O + SO₂↑',ionic:'SO₃²⁻ + 2H⁺ → H₂O + SO₂↑',explain:'يتكون حمض الكبريتوز غير الثابت ثم يتحلل إلى ماء وثاني أكسيد الكبريت.',tags:['غاز','رائحة نفاذة'],danger:true},
 'hcl_dil|thiosulfate': {kind:'gasSolid',gas:true,precipitate:true,precipColor:'#e6d765',gasName:'ثاني أكسيد الكبريت SO₂',obs:'يتصاعد غاز SO₂ ويتكون كبريت صلب دقيق يجعل المزيج عكرًا أصفر باهتًا.',conclusion:'تكوّن الكبريت مع تصاعد SO₂ يتفق مع وجود أيون الثيوكبريتات S₂O₃²⁻.',equation:'Na₂S₂O₃ + 2HCl → 2NaCl + H₂O + SO₂↑ + S↓',ionic:'S₂O₃²⁻ + 2H⁺ → H₂O + SO₂↑ + S↓',explain:'يتحلل أيون الثيوكبريتات في الوسط الحمضي مع تكوّن كبريت صلب وثاني أكسيد الكبريت.',tags:['غاز','راسب أصفر'],danger:true},
 'hcl_dil|sulfide': {kind:'gas',gas:true,gasName:'كبريتيد الهيدروجين H₂S',gasColorLabel:'غاز عديم اللون',gasTest:'ورقة خلات الرصاص تتحول إلى الأسود بسبب تكوّن PbS؛ لا يُشمّ الغاز.',obs:'قد يتصاعد غاز H₂S عديم اللون وشديد السمية. في الاختبار التأكيدي تسود ورقة خلات الرصاص بسبب تكوّن PbS. لا يُستنشق الغاز ولا يُحضّر خارج مختبر متخصص.',conclusion:'قد يشير التفاعل إلى وجود أيون الكبريتيد S²⁻، ويحتاج تحديده إلى اتباع منهج الكشف والاختبارات التأكيدية.',equation:'Na₂S + 2HCl → 2NaCl + H₂S↑',ionic:'S²⁻ + 2H⁺ → H₂S↑',explain:'يتحد أيون الكبريتيد مع أيونات الهيدروجين ويتكون غاز كبريتيد الهيدروجين.',tags:['غاز','تنبيه سلامة'],danger:true},
 'hcl_dil|nitrite': {kind:'gas',gas:true,gasName:'أكسيد النيتريك NO وثاني أكسيد النيتروجين NO₂',gasColor:'#a6533b',gasStroke:'#d28b73',gasColorLabel:'NO عديم اللون يتحوّل إلى NO₂ بني محمر',obs:'في الوسط الحمضي يتكون حمض النيتروز غير الثابت، وقد تتكون أكاسيد نيتروجين. لا يُجرى هذا التفاعل عمليًا خارج معمل مجهز.',conclusion:'النتيجة قد تتفق مع أيون النيتريت NO₂⁻، ويجب الرجوع إلى الاختبار التأكيدي الموضح في مذكرتك.',equation:'2NaNO₂ + 2HCl → 2NaCl + NO↑ + NO₂↑ + H₂O',ionic:'2NO₂⁻ + 2H⁺ → NO↑ + NO₂↑ + H₂O',explain:'حمض النيتروز غير ثابت وقد يحدث له تحلل ينتج أكاسيد النيتروجين.',tags:['غازات','تنبيه سلامة'],danger:true},
 'hcl_dil|silver_nitrate': {kind:'precipitate',precipitate:true,precipColor:'#f0f0e6',solidName:'كلوريد الفضة AgCl',obs:'يتكون راسب أبيض من كلوريد الفضة.',conclusion:'يؤكد ظهور الراسب وجود أيونات الفضة Ag⁺ في محلول نترات الفضة، أو أيونات الكلوريد في حالة أن محلول الملح هو العينة المجهولة. في هذه المحاكاة الملح المختار هو نترات الفضة.',equation:'AgNO₃ + HCl → AgCl↓ + HNO₃',ionic:'Ag⁺ + Cl⁻ → AgCl↓',explain:'كلوريد الفضة شحيح الذوبان في الماء، ولذلك يظهر على هيئة راسب أبيض.',tags:['راسب أبيض']},
 'hcl_dil|lead_nitrate': {kind:'precipitate',precipitate:true,precipColor:'#f1f0df',solidName:'كلوريد الرصاص PbCl₂',obs:'يتكون راسب أبيض من كلوريد الرصاص الثنائي؛ ذوبانيته تتأثر بدرجة الحرارة.',conclusion:'الراسب ناتج عن اجتماع أيونات الرصاص Pb²⁺ والكلوريد Cl⁻.',equation:'Pb(NO₃)₂ + 2HCl → PbCl₂↓ + 2HNO₃',ionic:'Pb²⁺ + 2Cl⁻ → PbCl₂↓',explain:'كلوريد الرصاص قليل الذوبان مقارنة بمعظم النترات، فيترسب من المحلول.',tags:['راسب أبيض']},
 'hcl_dil|chloride': {kind:'none',obs:'لا يُتوقع ظهور راسب أو غاز أو تغيّر مرئي واضح عند خلط هذين المحلولين في الظروف المعتادة.',conclusion:'لا يوجد تفاعل أيوني صافٍ يُلاحظ في هذه الحالة؛ فالأيونات تبقى ذائبة في الماء.',equation:'NaCl(aq) + HCl(aq) → لا تغير مرئي',ionic:'لا توجد معادلة أيونية صافية.',explain:'كلوريد الصوديوم وحمض الهيدروكلوريك إلكتروليتان قويان، ولا يتكوّن هنا راسب أو غاز أو مادة ضعيفة التأين.',tags:['لا تغير مرئي']},
 'hcl_dil|sodium_sulfate': {kind:'none',obs:'لا يُتوقع راسب أو غاز أو تغيّر مرئي واضح في الظروف المعتادة.',conclusion:'لا يوجد تفاعل أيوني صافٍ ملحوظ بين الأيونات في هذا الزوج.',equation:'Na₂SO₄(aq) + HCl(aq) → لا تغير مرئي',ionic:'لا توجد معادلة أيونية صافية.',explain:'الأيونات الناتجة تظل ذائبة ولا تتكون مادة دافعة للتفاعل في الظروف المحددة.',tags:['لا تغير مرئي']},
 'h2so4_dil|carbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'يحدث فوران ويتصاعد غاز عديم اللون هو ثاني أكسيد الكربون.',conclusion:'يتفق ذلك مع وجود كربونات في الملح.',equation:'Na₂CO₃ + H₂SO₄ → Na₂SO₄ + H₂O + CO₂↑',ionic:'CO₃²⁻ + 2H⁺ → H₂O + CO₂↑',explain:'يتفاعل الكربونات مع الحمض ويتحرر ثاني أكسيد الكربون.',tags:['غاز','فوران']},
 'h2so4_dil|bicarbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'يحدث فوران ويتصاعد غاز ثاني أكسيد الكربون.',conclusion:'تتفق المشاهدة مع وجود أيون البيكربونات.',equation:'2NaHCO₃ + H₂SO₄ → Na₂SO₄ + 2H₂O + 2CO₂↑',ionic:'HCO₃⁻ + H⁺ → H₂O + CO₂↑',explain:'يحرر الحمض ثاني أكسيد الكربون من أيون البيكربونات.',tags:['غاز','فوران']},
 'h2so4_dil|sulfite': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكبريت SO₂',gasColorLabel:'غاز عديم اللون',gasTest:'ورقة مبللة بثنائي كرومات البوتاسيوم المحمّضة تتحول من البرتقالي إلى الأخضر.',obs:'يتصاعد غاز SO₂ عديم اللون ذو خواص مهيجة؛ وفي اختباره يتحول لون ورقة ثنائي كرومات البوتاسيوم المحمّضة من البرتقالي إلى الأخضر. لا يُشمّ الغاز.',conclusion:'قد يدل ذلك على وجود أيون الكبريتيت SO₃²⁻.',equation:'Na₂SO₃ + H₂SO₄ → Na₂SO₄ + H₂O + SO₂↑',ionic:'SO₃²⁻ + 2H⁺ → H₂O + SO₂↑',explain:'يحرر الحمض الضعيف المتكون من الكبريتيت غاز ثاني أكسيد الكبريت.',tags:['غاز','تنبيه سلامة'],danger:true},
 'h2so4_dil|thiosulfate': {kind:'gasSolid',gas:true,precipitate:true,precipColor:'#e4d75e',gasName:'ثاني أكسيد الكبريت SO₂',gasColorLabel:'غاز عديم اللون',gasTest:'ورقة ثنائي كرومات البوتاسيوم المحمّضة تتحول من البرتقالي إلى الأخضر.',obs:'يتصاعد غاز SO₂ عديم اللون ويتكون كبريت صلب أصفر باهت يجعل المحلول عكرًا؛ ورقة ثنائي كرومات البوتاسيوم المحمّضة تتحول إلى الأخضر عند اختبار الغاز.',conclusion:'تتفق المشاهدة مع وجود أيون الثيوكبريتات S₂O₃²⁻.',equation:'Na₂S₂O₃ + H₂SO₄ → Na₂SO₄ + H₂O + SO₂↑ + S↓',ionic:'S₂O₃²⁻ + 2H⁺ → H₂O + SO₂↑ + S↓',explain:'يتحلل الثيوكبريتات في الوسط الحمضي مكونًا كبريتًا صلبًا وغاز SO₂.',tags:['راسب أصفر','غاز'],danger:true},
 'h2so4_dil|sulfide': {kind:'gas',gas:true,gasName:'كبريتيد الهيدروجين H₂S',gasColorLabel:'غاز عديم اللون',gasTest:'ورقة خلات الرصاص تتحول إلى الأسود بسبب تكوّن PbS؛ لا يُشمّ الغاز.',obs:'قد يتصاعد غاز H₂S عديم اللون وشديد السمية. ورقة خلات الرصاص تسود بسبب تكوّن PbS. هذا وصف نظري فقط؛ لا تحاول توليده أو استنشاقه.',conclusion:'قد يدل التفاعل على وجود أيون الكبريتيد S²⁻.',equation:'Na₂S + H₂SO₄ → Na₂SO₄ + H₂S↑',ionic:'S²⁻ + 2H⁺ → H₂S↑',explain:'تتحد أيونات الكبريتيد مع الهيدروجين لتكوين كبريتيد الهيدروجين.',tags:['غاز','تنبيه سلامة'],danger:true},
 'h2so4_dil|barium_chloride': {kind:'precipitate',precipitate:true,precipColor:'#f2f2e8',solidName:'كبريتات الباريوم BaSO₄',obs:'يتكون راسب أبيض كثيف من كبريتات الباريوم.',conclusion:'يدل الراسب على وجود أيونات الباريوم Ba²⁺ في الملح المحدد، أو على الكبريتات إذا كان محلول الباريوم هو الكاشف والعينة تحتوي على SO₄²⁻. هنا الملح المختار هو كلوريد الباريوم.',equation:'BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl',ionic:'Ba²⁺ + SO₄²⁻ → BaSO₄↓',explain:'كبريتات الباريوم شديدة الانخفاض في الذوبانية فتظهر كراسب أبيض.',tags:['راسب أبيض']},
 'h2so4_dil|lead_nitrate': {kind:'precipitate',precipitate:true,precipColor:'#f0efe3',solidName:'كبريتات الرصاص PbSO₄',obs:'يتكون راسب أبيض من كبريتات الرصاص.',conclusion:'يتحد Pb²⁺ مع SO₄²⁻ مكوِّنًا ملحًا شحيح الذوبان.',equation:'Pb(NO₃)₂ + H₂SO₄ → PbSO₄↓ + 2HNO₃',ionic:'Pb²⁺ + SO₄²⁻ → PbSO₄↓',explain:'كبريتات الرصاص قليلة الذوبان ولذلك تترسب.',tags:['راسب أبيض']},
 'h2so4_dil|chloride': {kind:'none',obs:'لا يُتوقع تغيّر مرئي واضح عند خلط المحاليل المخففة في الظروف المعتادة.',conclusion:'لا يوجد تفاعل أيوني صافٍ يُلاحظ في هذا الزوج ضمن الظروف المذكورة.',equation:'NaCl(aq) + H₂SO₄(aq) → لا تغير مرئي',ionic:'لا توجد معادلة أيونية صافية.',explain:'في المحاليل المخففة لا ينتج هنا راسب أو غاز في الظروف المعتادة.',tags:['لا تغير مرئي']},
 'h2so4_conc|chloride': {kind:'gas',gas:true,gasName:'كلوريد الهيدروجين HCl',obs:'في الوصف المدرسي للتفاعل مع كلوريد صلب وحمض كبريتيك مركز، يتصاعد غاز HCl عديم اللون ذي أبخرة مهيجة في الهواء الرطب.',conclusion:'هذا تفاعل تحضير/تحرير لغاز كلوريد الهيدروجين من كلوريد صلب، وليس اختبارًا بصريًا فريدًا لتأكيد الكلوريد وحده.',equation:'NaCl(s) + H₂SO₄(conc) → NaHSO₄(s) + HCl↑',ionic:'يُعرض هنا التمثيل الجزيئي المدرسي؛ تفاصيل الحالة تعتمد على ظروف المنهج.',explain:'حمض الكبريتيك المركز أقل تطايرًا من HCl، فيزيح الحمض المتطاير من ملحه في التمثيل الدراسي.',tags:['غاز','حمض مركز'],danger:true},
 'h2so4_conc|bromide': {kind:'gas',gas:true,gasName:'أبخرة البروم وثاني أكسيد الكبريت',gasColor:'#a6533b',gasStroke:'#d28b73',gasColorLabel:'أبخرة بروم بنية محمرة',obs:'قد تتكون أبخرة بروم بنية/بنية محمرة مع نواتج اختزال أخرى. نواتج هذا التفاعل خطرة ومذكورة هنا للمذاكرة فقط.',conclusion:'المشاهدة البنية تتفق مع تكون البروم، بينما يعمل Br⁻ عاملًا مختزلًا في وجود H₂SO₄ المركز.',equation:'2KBr + 3H₂SO₄(conc) → 2KHSO₄ + Br₂ + SO₂↑ + 2H₂O',ionic:'تفاعل أكسدة واختزال؛ تُراجع تفاصيله حسب صياغة المنهج.',explain:'حمض الكبريتيك المركز يعمل مؤكسدًا مع البروميد، فتتكون نواتج متعددة.',tags:['أبخرة بنية','أكسدة واختزال'],danger:true},
 'h2so4_conc|iodide': {kind:'gasSolid',gas:true,precipitate:true,precipColor:'#6d4b27',gasName:'أبخرة يود ونواتج اختزال متعددة',gasColor:'#8060b2',gasStroke:'#b59ade',gasColorLabel:'أبخرة يود بنفسجية',obs:'يمكن أن تظهر أبخرة يود بنفسجية وتتكون نواتج اختزال للحمض. المشهد يرمز إلى نواتج متعددة ولا يحاكي الكميات أو المسارات التفصيلية.',conclusion:'أيون اليوديد عامل مختزل أقوى من البروميد، وقد يختزل حمض الكبريتيك المركز إلى نواتج مختلفة.',equation:'8KI + 9H₂SO₄(conc) → 8KHSO₄ + 4I₂ + H₂S↑ + 4H₂O',ionic:'تفاعل أكسدة واختزال مع احتمال نواتج متعددة وفق ظروف التفاعل.',explain:'يؤكسد الحمض المركز اليوديد إلى اليود ويُختزل جزء من الكبريت في الحمض.',tags:['أبخرة يود','تفاعل معقد'],danger:true},
 'h2so4_conc|potassium_nitrate': {kind:'gas',gas:true,gasName:'حمض النيتريك المتطاير',obs:'في الوصف الدراسي يمكن أن يتحرر حمض النيتريك من ملح النترات عند تفاعله مع حمض الكبريتيك المركز.',conclusion:'هذا تفاعل إزاحة لحمض متطاير؛ ليس اختبارًا مرئيًا مستقلًا لتأكيد أيون النترات.',equation:'KNO₃(s) + H₂SO₄(conc) → KHSO₄(s) + HNO₃↑',ionic:'التمثيل الجزيئي أعلاه تعليمي، والحالات الفعلية تعتمد على الشروط.',explain:'حمض الكبريتيك المركز يزيح حمض النيتريك من ملح النترات في التمثيل المقرر.',tags:['حمض متطاير','حمض مركز'],danger:true},
 'hno3_dil|carbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'يحدث فوران مع تصاعد غاز عديم اللون هو CO₂.',conclusion:'يتفق التفاعل مع وجود أيون الكربونات.',equation:'Na₂CO₃ + 2HNO₃ → 2NaNO₃ + H₂O + CO₂↑',ionic:'CO₃²⁻ + 2H⁺ → H₂O + CO₂↑',explain:'الحمض يتفاعل مع أيون الكربونات مطلقًا ثاني أكسيد الكربون.',tags:['غاز','فوران']},
 'hno3_dil|bicarbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'يحدث فوران ويتصاعد ثاني أكسيد الكربون.',conclusion:'يتفق التفاعل مع وجود أيون البيكربونات.',equation:'NaHCO₃ + HNO₃ → NaNO₃ + H₂O + CO₂↑',ionic:'HCO₃⁻ + H⁺ → H₂O + CO₂↑',explain:'يتفاعل الحمض مع البيكربونات مطلقًا CO₂.',tags:['غاز','فوران']},
 'acetic|carbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'قد يحدث فوران ويتصاعد CO₂، ويكون التفاعل مع الحمض الضعيف أبطأ من حمض قوي عند ظروف مماثلة.',conclusion:'يتفق التفاعل مع وجود أيون الكربونات.',equation:'Na₂CO₃ + 2CH₃COOH → 2CH₃COONa + H₂O + CO₂↑',ionic:'CO₃²⁻ + 2H⁺ → H₂O + CO₂↑ (تمثيل مبسط)',explain:'حمض الإيثانويك يتفاعل مع الكربونات وينتج ثاني أكسيد الكربون.',tags:['غاز','فوران']},
 'acetic|bicarbonate': {kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',obs:'قد يحدث فوران ويتصاعد CO₂.',conclusion:'يتفق التفاعل مع وجود أيون البيكربونات.',equation:'NaHCO₃ + CH₃COOH → CH₃COONa + H₂O + CO₂↑',ionic:'HCO₃⁻ + H⁺ → H₂O + CO₂↑ (تمثيل مبسط)',explain:'يتفاعل الحمض مع البيكربونات مطلقًا ثاني أكسيد الكربون.',tags:['غاز','فوران']}
};

const confirmatoryTests = {
 carbonate: [
  {id:'carbonate_mgso4',title:'محلول كبريتات المغنيسيوم MgSO₄',badge:'على البارد',kind:'precipitate',precipitate:true,precipColor:'#f3f1e7',solidName:'كربونات المغنيسيوم MgCO₃',solidColorLabel:'أبيض',obs:'يتكوّن راسب أبيض على البارد من كربونات المغنيسيوم.',conclusion:'يدعم ذلك وجود أيون الكربونات CO₃²⁻. الراسب يذوب في الحمض المخفف مع تصاعد CO₂.',equation:'Na₂CO₃ + MgSO₄ → MgCO₃↓ + Na₂SO₄',ionic:'Mg²⁺ + CO₃²⁻ → MgCO₃↓',explain:'كربونات المغنيسيوم شحيحة الذوبان؛ لذلك تخرج من المحلول في صورة راسب أبيض.'},
  {id:'carbonate_dissolve',title:'ذوبان راسب MgCO₃ في HCl المخفف',badge:'اختبار متابعة',kind:'gas',gas:true,gasName:'ثاني أكسيد الكربون CO₂',gasColor:'#d8f4fb',gasColorLabel:'عديم اللون',obs:'يذوب الراسب الأبيض ويحدث فوران بسبب انطلاق CO₂.',conclusion:'انطلاق CO₂ عند إذابة الراسب في الحمض يتفق مع كربونات المغنيسيوم.',equation:'MgCO₃ + 2HCl → MgCl₂ + H₂O + CO₂↑',ionic:'MgCO₃(s) + 2H⁺ → Mg²⁺ + H₂O + CO₂↑',explain:'يتفاعل الكربونات مع الحمض، ويتكوّن ماء وغاز ثاني أكسيد الكربون.'},
  {id:'carbonate_limewater',title:'اختبار غاز CO₂ بماء الجير الرائق',badge:'تأكيد الغاز',kind:'precipitate',precipitate:true,precipColor:'#f2f0df',solidName:'كربونات الكالسيوم CaCO₃',solidColorLabel:'أبيض لبني',obs:'يتعكّر ماء الجير الرائق بسبب تكوّن راسب أبيض من CaCO₃ عند مرور CO₂ مدة قصيرة.',conclusion:'تعكّر ماء الجير دليل مدرسي على CO₂. مرور الغاز مدة طويلة قد يزيل التعكّر بسبب تكوّن بيكربونات كالسيوم ذائبة.',equation:'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',ionic:'CO₂ + Ca²⁺ + 2OH⁻ → CaCO₃↓ + H₂O',explain:'يتفاعل ثاني أكسيد الكربون مع ماء الجير مكوّنًا كربونات الكالسيوم قليلة الذوبان.'}
 ],
 bicarbonate: [
  {id:'bicarbonate_mgso4cold',title:'محلول كبريتات المغنيسيوم MgSO₄',badge:'على البارد',kind:'none',obs:'لا يتكوّن راسب على البارد؛ يبقى بيكربونات المغنيسيوم ذائبة في المحلول.',conclusion:'عدم ظهور راسب على البارد يساعد على التفرقة بين البيكربونات والكربونات.',equation:'2NaHCO₃ + MgSO₄ → Na₂SO₄ + Mg(HCO₃)₂(aq)',ionic:'Mg²⁺ + 2HCO₃⁻ → Mg(HCO₃)₂(aq)',explain:'بيكربونات المغنيسيوم ذائبة في الماء في هذه الظروف؛ لذلك لا يظهر راسب مرئي.'},
  {id:'bicarbonate_mgso4heat',title:'تسخين مزيج البيكربونات وMgSO₄',badge:'بعد التسخين',kind:'gasSolid',gas:true,precipitate:true,precipColor:'#f0eee3',solidName:'كربونات المغنيسيوم MgCO₃',solidColorLabel:'أبيض',gasName:'ثاني أكسيد الكربون CO₂',gasColor:'#d8f4fb',gasColorLabel:'عديم اللون',obs:'بعد التسخين يتكوّن راسب أبيض مع انطلاق غاز CO₂.',conclusion:'الفرق الأساسي: الكربونات تعطي الراسب الأبيض مع MgSO₄ على البارد، أما البيكربونات فتظهر الراسب بعد التسخين.',equation:'2NaHCO₃ + MgSO₄ → Na₂SO₄ + MgCO₃↓ + H₂O + CO₂↑  (بالتسخين)',ionic:'Mg²⁺ + 2HCO₃⁻ → MgCO₃↓ + H₂O + CO₂↑  (Δ)',explain:'تتكوّن بيكربونات المغنيسيوم الذائبة أولًا، ثم تتحلل بالحرارة إلى كربونات مغنيسيوم وماء وثاني أكسيد الكربون.'},
  {id:'bicarbonate_limewater',title:'اختبار غاز CO₂ بماء الجير الرائق',badge:'تأكيد الغاز',kind:'precipitate',precipitate:true,precipColor:'#f2f0df',solidName:'كربونات الكالسيوم CaCO₃',solidColorLabel:'أبيض لبني',obs:'يتعكّر ماء الجير الرائق نتيجة تكوّن كربونات الكالسيوم.',conclusion:'يثبت CO₂ الناتج، لكنه وحده لا يميّز الكربونات من البيكربونات؛ يتم التفريق باختبار MgSO₄ على البارد ثم بالتسخين.',equation:'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O',ionic:'CO₂ + Ca²⁺ + 2OH⁻ → CaCO₃↓ + H₂O',explain:'الكربونات والبيكربونات كلتاهما قد تطلقان CO₂ مع الحمض؛ الاختبار التفريقي هو سلوك MgSO₄.'}
 ],
 sulfite: [
  {id:'sulfite_dichromate',title:'ورقة مبللة بثنائي كرومات البوتاسيوم المحمّضة',badge:'برتقالي ← أخضر',kind:'solution',visualType:'paper',paperColor:'#4e986b',paperStartColor:'#e49b34',paperLabel:'ورقة ثنائي كرومات: برتقالي ← أخضر',solutionColor:'#4e986b',solutionName:'ورقة ثنائي كرومات البوتاسيوم المحمّضة',solutionColorLabel:'يتحوّل لون الكاشف من البرتقالي إلى الأخضر',obs:'غاز SO₂ نفسه عديم اللون؛ الذي يتغيّر لونه هو ورقة الكاشف المبللة بثنائي كرومات البوتاسيوم المحمّضة، من البرتقالي إلى الأخضر نتيجة اختزال Cr(VI) إلى Cr(III).',conclusion:'تحوّل ورقة ثنائي كرومات البوتاسيوم المحمّضة من البرتقالي إلى الأخضر هو اختبار تأكيدي لغاز SO₂ الناتج من الكبريتيت.',equation:'K₂Cr₂O₇ + 3SO₂ + H₂SO₄ → K₂SO₄ + Cr₂(SO₄)₃ + H₂O',ionic:'Cr₂O₇²⁻ + 3SO₂ + 2H⁺ → 2Cr³⁺ + 3SO₄²⁻ + H₂O',explain:'ثاني أكسيد الكبريت عامل مختزل؛ يحوّل أيونات الكروم من حالة +6 البرتقالية إلى +3 الخضراء.',danger:true},
  {id:'sulfite_silver',title:'محلول نترات الفضة AgNO₃',badge:'راسب تأكيدي',kind:'precipitate',precipitate:true,precipColor:'#f2f0e4',solidName:'كبريتيت الفضة Ag₂SO₃',solidColorLabel:'أبيض',obs:'يتكوّن راسب أبيض من كبريتيت الفضة؛ قد يتغير لونه عند التسخين أو التحلل.',conclusion:'يتوافق الراسب مع الكبريتيت، وتُراجع تفاصيل التسخين كما يعرضها المنهج.',equation:'Na₂SO₃ + 2AgNO₃ → Ag₂SO₃↓ + 2NaNO₃',ionic:'2Ag⁺ + SO₃²⁻ → Ag₂SO₃↓',explain:'يتحد Ag⁺ مع SO₃²⁻ ليكوّن مركبًا قليل الذوبان.'}
 ],
 sulfide: [
  {id:'sulfide_lead',title:'اختبار تأكيدي لغاز كبريتيد الهيدروجين بورقة خلات الرصاص',badge:'الورقة تسودّ',kind:'precipitate',visualType:'paper',paperColor:'#24272e',paperStartColor:'#f3eddd',paperLabel:'اسوداد ورقة خلات الرصاص',solidLocation:'على ورقة خلات الرصاص',precipitate:true,precipColor:'#24272e',solidName:'كبريتيد الرصاص PbS',solidColorLabel:'أسود',obs:'تتحول ورقة خلات الرصاص إلى اللون الأسود عند ملامسة غاز H₂S؛ اللون ناتج عن تكوّن كبريتيد الرصاص PbS.',conclusion:'اسوداد ورقة خلات الرصاص هو الاختبار التأكيدي لغاز كبريتيد الهيدروجين الناتج من تفاعل الكبريتيد مع الحمض.',equation:'H₂S(g) + Pb(CH₃COO)₂(aq) → PbS(s)↓ + 2CH₃COOH(aq)',ionic:'Pb²⁺ + H₂S → PbS↓ + 2H⁺',explain:'الاختبار هنا للغاز H₂S نفسه: يتفاعل مع خلات الرصاص على الورقة ويكوّن كبريتيد الرصاص الأسود. كبريتيد الرصاص شديد الانخفاض في الذوبانية.',danger:true},
  {id:'sulfide_silver',title:'اختبار أيون الكبريتيد في المحلول بنترات الفضة (ليس اختبار الغاز)',badge:'اختبار أيون S²⁻',kind:'precipitate',precipitate:true,precipColor:'#20242b',solidName:'كبريتيد الفضة Ag₂S',solidColorLabel:'أسود',obs:'يتكوّن راسب أسود من كبريتيد الفضة.',conclusion:'الراسب الأسود يتفق مع وجود أيون الكبريتيد S²⁻.',equation:'Na₂S + 2AgNO₃ → Ag₂S↓ + 2NaNO₃',ionic:'2Ag⁺ + S²⁻ → Ag₂S↓',explain:'يتحد أيون الفضة مع الكبريتيد لتكوين كبريتيد الفضة غير الذائب.',danger:true}
 ],
 thiosulfate: [
  {id:'thiosulfate_iodine',title:'محلول اليود البني',badge:'اختبار إزالة لون',kind:'solution',solutionColor:'#d8e7e7',solutionColorLabel:'يختفي اللون البني لليود',obs:'يزول اللون البني لليود عند تفاعله مع الثيوكبريتات، ويتكوّن رباعي الثيونات.',conclusion:'اختفاء لون اليود يتفق مع وجود أيون الثيوكبريتات S₂O₃²⁻.',equation:'2Na₂S₂O₃ + I₂ → Na₂S₄O₆ + 2NaI',ionic:'2S₂O₃²⁻ + I₂ → S₄O₆²⁻ + 2I⁻',explain:'تُختزل جزيئات اليود إلى أيونات يوديد عديمة اللون، بينما تتأكسد الثيوكبريتات إلى رباعي الثيونات.'},
  {id:'thiosulfate_so2_dichromate',title:'اختبار غاز SO₂ بورقة ثنائي كرومات البوتاسيوم المحمّضة',badge:'برتقالي ← أخضر',kind:'solution',visualType:'paper',paperColor:'#4e986b',paperStartColor:'#e49b34',paperLabel:'ورقة ثنائي كرومات: برتقالي ← أخضر',solutionColor:'#4e986b',solutionName:'ورقة الكاشف بعد التفاعل',solutionColorLabel:'أخضر',obs:'يتصاعد SO₂ عديم اللون في التفاعل الأساسي؛ وعند اختباره يتغير لون ورقة ثنائي كرومات البوتاسيوم المحمّضة من البرتقالي إلى الأخضر.',conclusion:'هذا الاختبار للكشف عن غاز SO₂ الناتج، وليس لأن الغاز نفسه أخضر اللون.',equation:'K₂Cr₂O₇ + 3SO₂ + H₂SO₄ → K₂SO₄ + Cr₂(SO₄)₃ + H₂O',ionic:'Cr₂O₇²⁻ + 3SO₂ + 2H⁺ → 2Cr³⁺ + 3SO₄²⁻ + H₂O',explain:'يختزل SO₂ ثنائي كرومات البوتاسيوم البرتقالي إلى أيونات الكروم الثلاثي الخضراء.',danger:true}
 ],
 nitrite: [
  {id:'nitrite_permanganate',title:'برمنجنات البوتاسيوم المحمّضة KMnO₄',badge:'اختبار لوني',kind:'solution',solutionColor:'#e9eef0',solutionColorLabel:'يزول البنفسجي',obs:'يزول اللون البنفسجي لبرمنجنات البوتاسيوم المحمّضة مع أكسدة النيتريت إلى نترات.',conclusion:'زوال اللون البنفسجي يتفق مع وجود أيون النيتريت NO₂⁻.',equation:'5NaNO₂ + 2KMnO₄ + 3H₂SO₄ → 5NaNO₃ + K₂SO₄ + 2MnSO₄ + 3H₂O',ionic:'5NO₂⁻ + 2MnO₄⁻ + 6H⁺ → 5NO₃⁻ + 2Mn²⁺ + 3H₂O',explain:'يتأكسد NO₂⁻ إلى NO₃⁻، وتُختزل أيونات البرمنجنات البنفسجية إلى Mn²⁺ الباهتة.',danger:true}
 ],
 chloride: [
  {id:'chloride_silver',title:'محلول نترات الفضة AgNO₃',badge:'راسب أبيض',kind:'precipitate',precipitate:true,precipColor:'#f5f3e9',solidName:'كلوريد الفضة AgCl',solidColorLabel:'أبيض جبني',obs:'يتكوّن راسب أبيض جبني من كلوريد الفضة.',conclusion:'يدعم ذلك وجود Cl⁻. للتأكيد الإضافي، يذوب AgCl في محلول الأمونيا ويعود راسبًا عند التحميض.',equation:'NaCl + AgNO₃ → AgCl↓ + NaNO₃',ionic:'Ag⁺ + Cl⁻ → AgCl↓',explain:'كلوريد الفضة شحيح الذوبان في الماء.'},
  {id:'chloride_ammonia',title:'ذوبان راسب AgCl في الأمونيا',badge:'تمييز الهاليدات',kind:'none',solutionColor:'#b9d8e2',solutionColorLabel:'يذوب الراسب الأبيض',obs:'يذوب راسب كلوريد الفضة في محلول الأمونيا بسبب تكوّن معقّد الفضة الذائب.',conclusion:'الذوبان في الأمونيا يميّز AgCl عن AgI، بينما يحتاج AgBr إلى أمونيا أكثر تركيزًا.',equation:'AgCl(s) + 2NH₃(aq) ⇌ [Ag(NH₃)₂]⁺(aq) + Cl⁻(aq)',ionic:'AgCl(s) + 2NH₃ ⇌ [Ag(NH₃)₂]⁺ + Cl⁻',explain:'تكوّن أيون المعقّد الذائب يسحب Ag⁺ من الراسب فيساعد على ذوبانه.'}
 ],
 bromide: [
  {id:'bromide_silver',title:'محلول نترات الفضة AgNO₃',badge:'راسب كريمي',kind:'precipitate',precipitate:true,precipColor:'#e7d8a9',solidName:'بروميد الفضة AgBr',solidColorLabel:'كريمي باهت',obs:'يتكوّن راسب كريمي باهت من بروميد الفضة.',conclusion:'لون AgBr أغمق من AgCl وأفتح من AgI؛ ذوبانه في الأمونيا أصعب من AgCl.',equation:'KBr + AgNO₃ → AgBr↓ + KNO₃',ionic:'Ag⁺ + Br⁻ → AgBr↓',explain:'بروميد الفضة قليل الذوبان ويظهر بلون كريمي.'},
  {id:'bromide_ammonia',title:'اختبار ذوبانية AgBr في الأمونيا',badge:'تمييز الهاليدات',kind:'none',obs:'لا يذوب AgBr في الأمونيا المخففة بسهولة، ويذوب في الأمونيا المركّزة وفق شروط الاختبار المدرسي.',conclusion:'هذه الذوبانية المتوسطة تساعد على تمييز البروميد عن الكلوريد واليوديد.',equation:'AgBr(s) + 2NH₃(aq) ⇌ [Ag(NH₃)₂]⁺(aq) + Br⁻(aq)  (في NH₃ المركّز)',ionic:'AgBr(s) + 2NH₃ ⇌ [Ag(NH₃)₂]⁺ + Br⁻',explain:'يختلف اتزان ذوبان هاليدات الفضة وتكوين معقّداتها مع الأمونيا بحسب نوع الهاليد.'}
 ],
 iodide: [
  {id:'iodide_silver',title:'محلول نترات الفضة AgNO₃',badge:'راسب أصفر',kind:'precipitate',precipitate:true,precipColor:'#f2d34f',solidName:'يوديد الفضة AgI',solidColorLabel:'أصفر',obs:'يتكوّن راسب أصفر من يوديد الفضة.',conclusion:'AgI لا يذوب في الأمونيا؛ يُستفاد من ذلك في التفرقة بين الهاليدات.',equation:'KI + AgNO₃ → AgI↓ + KNO₃',ionic:'Ag⁺ + I⁻ → AgI↓',explain:'يوديد الفضة شديد الانخفاض في الذوبانية.'},
  {id:'iodide_ammonia',title:'اختبار ذوبانية AgI في الأمونيا',badge:'تمييز الهاليدات',kind:'precipitate',precipitate:true,precipColor:'#f2d34f',solidName:'يوديد الفضة AgI',solidColorLabel:'أصفر لا يذوب',obs:'يبقى الراسب الأصفر كما هو في الأمونيا المخففة والمركّزة.',conclusion:'عدم الذوبان في الأمونيا يميّز يوديد الفضة عن كلوريد الفضة وبروميد الفضة.',equation:'AgI(s) + NH₃(aq) → لا ذوبان ملحوظ',ionic:'يبقى AgI(s) راسبًا.',explain:'شدة انخفاض ذوبانية AgI تمنع تكوين كمية كافية من معقّد الفضة الذائب في هذه الظروف.'}
 ],
 sodium_sulfate: [
  {id:'sulfate_barium',title:'كلوريد الباريوم BaCl₂ بعد تحميض العينة بـ HCl المخفف',badge:'راسب أبيض ثابت',kind:'precipitate',precipitate:true,precipColor:'#f4f3e9',solidName:'كبريتات الباريوم BaSO₄',solidColorLabel:'أبيض كثيف',obs:'يتكوّن راسب أبيض كثيف من BaSO₄ ولا يذوب في الحمض المخفف.',conclusion:'تكوّن الراسب الأبيض الثابت بعد التحميض يتفق مع وجود SO₄²⁻.',equation:'Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl',ionic:'Ba²⁺ + SO₄²⁻ → BaSO₄↓',explain:'كبريتات الباريوم شديدة الانخفاض في الذوبانية؛ ويُحمّض محلول العينة أولًا لمنع تداخل بعض الأيونات.'}
 ],
 sodium_nitrate: [
  {id:'nitrate_brownring',title:'اختبار الحلقة البنية (عرض نظري)',badge:'اختبار تأكيدي',kind:'solution',solutionColor:'#8b4d2e',solutionColorLabel:'حلقة بنية عند الحد الفاصل',obs:'في الاختبار المدرسي تظهر حلقة بنية عند الحد الفاصل بين طبقتي المحلول نتيجة تكوّن معقّد نيتروسيل الحديد.',conclusion:'الحلقة البنية علامة تأكيدية للنترات ضمن شروط الاختبار المدرسي؛ المعاينة هنا محاكاة فقط.',equation:'NO₃⁻ + 3Fe²⁺ + 4H⁺ → NO + 3Fe³⁺ + 2H₂O',ionic:'NO يتناسق مع Fe²⁺ مكوّنًا معقّدًا نيتروسيلّيًا بني اللون.',explain:'يتحول جزء من النترات إلى NO، الذي يكوّن معقّدًا بنيًا مع الحديد الثنائي.',danger:true}
 ],
 potassium_nitrate: [
  {id:'nitrate_brownring2',title:'اختبار الحلقة البنية (عرض نظري)',badge:'اختبار تأكيدي',kind:'solution',solutionColor:'#8b4d2e',solutionColorLabel:'حلقة بنية عند الحد الفاصل',obs:'تظهر حلقة بنية عند الحد الفاصل في اختبار الحلقة البنية.',conclusion:'تتفق الحلقة البنية مع وجود أيون النترات NO₃⁻ في اختبار تأكيدي معروف.',equation:'NO₃⁻ + 3Fe²⁺ + 4H⁺ → NO + 3Fe³⁺ + 2H₂O',ionic:'يتكوّن معقّد نيتروسيل الحديد ذي اللون البني.',explain:'تُعرض النتيجة للشرح النظري فقط، لأن الاختبار يتضمن أحماضًا مركزة.' ,danger:true}
 ],
 sodium_phosphate: [
  {id:'phosphate_silver',title:'محلول نترات الفضة AgNO₃',badge:'راسب أصفر',kind:'precipitate',precipitate:true,precipColor:'#e6c84c',solidName:'فوسفات الفضة Ag₃PO₄',solidColorLabel:'أصفر',obs:'يتكوّن راسب أصفر من فوسفات الفضة.',conclusion:'يتفق الراسب الأصفر مع وجود أيون الفوسفات PO₄³⁻.',equation:'Na₃PO₄ + 3AgNO₃ → Ag₃PO₄↓ + 3NaNO₃',ionic:'3Ag⁺ + PO₄³⁻ → Ag₃PO₄↓',explain:'فوسفات الفضة قليل الذوبان ويتميّز بلونه الأصفر.'}
 ]
};


const gasProperties = {
  co2: {name:'ثاني أكسيد الكربون CO₂', appearance:'عديم اللون والرائحة', test:'ماء الجير الرائق يتعكّر بسبب تكوّن راسب أبيض من كربونات الكالسيوم CaCO₃.', testEquation:'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O', color:'#d8f4fb'},
  so2: {name:'ثاني أكسيد الكبريت SO₂', appearance:'غاز عديم اللون', test:'ورقة مبللة بثنائي كرومات البوتاسيوم المحمّضة: يتغير لون الكاشف من البرتقالي إلى الأخضر. الغاز نفسه ليس أخضر.', testEquation:'K₂Cr₂O₇ + 3SO₂ + H₂SO₄ → K₂SO₄ + Cr₂(SO₄)₃ + H₂O', color:'#d8f4fb'},
  h2s: {name:'كبريتيد الهيدروجين H₂S', appearance:'غاز عديم اللون وشديد السمية', test:'ورقة خلات الرصاص تتحول إلى الأسود نتيجة تكوّن كبريتيد الرصاص PbS. لا يُشمّ الغاز.', testEquation:'H₂S + Pb(CH₃COO)₂ → PbS↓ + 2CH₃COOH', color:'#d8f4fb'},
  co: {name:'أول أكسيد الكربون CO', appearance:'غاز عديم اللون والرائحة وشديد السمية', test:'لا يعتمد كشفه على اللون أو الرائحة؛ لا يدخل ضمن الاختبارات المدرسية المعتادة لهذا الباب.', color:'#d8f4fb'},
  no2: {name:'ثاني أكسيد النيتروجين NO₂', appearance:'غاز بني محمر ومهيّج', test:'لونه البني المحمر هو الملاحظة البصرية المميزة في وصف التفاعل. لا يُستنشق.', color:'#a6533b'},
  no: {name:'أكسيد النيتريك NO', appearance:'غاز عديم اللون؛ يتأكسد بالهواء إلى NO₂ بني محمر', test:'قد يظهر اللون البني المحمر بعد تعرضه للهواء بسبب تكوّن NO₂.', color:'#d8f4fb'},
  hcl: {name:'كلوريد الهيدروجين HCl', appearance:'غاز عديم اللون؛ قد تظهر أبخرة بيضاء في الهواء الرطب', test:'يكون أبخرة بيضاء مع الأمونيا بسبب تكوّن كلوريد الأمونيوم؛ هذه ملاحظة نظرية للمذاكرة.', testEquation:'HCl + NH₃ → NH₄Cl', color:'#d8f4fb'},
  br2: {name:'البروم Br₂', appearance:'أبخرة بنية محمرة', test:'اللون البني المحمر للأبخرة من الملاحظات المميزة في تفاعلات البروميد مع حمض الكبريتيك المركز.', color:'#a6533b'},
  i2: {name:'اليود I₂', appearance:'أبخرة بنفسجية', test:'قد تظهر أبخرة اليود البنفسجية في تفاعلات اليوديد مع حمض الكبريتيك المركز.', color:'#8666b4'},
  cl2: {name:'الكلور Cl₂', appearance:'غاز أصفر مخضر وسام', test:'لونه أصفر مخضر؛ لا يُحضّر أو يُستنشق خارج مختبر مجهز.', color:'#b6b75c'}
};

